name: PowerSophia
favicon: null
layout_spectrum: 0.85706
typography_spectrum: 0.93305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9dc9a6'
    - '#ffffff'
    - '#590401'
    - '#c44d49'
    - '#cfc100'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
